module.exports = [
    'var welcome = \'to scriptie-talkie\';'
  , ''
  , 'function whatDoesItDo() {'
  , '  return  \'scriptie-talkie evaluates your script snippet by snippet\\n\''
  , '        + \'and prints intermediate results and context changes\';'
  , '}'
  , ''
  , 'whatDoesItDo();'
  , ''
  , '// For example'
  , '// you can assign variables'
  , 'var a = 1;'
  , ''
  , '// and modify them while assigning more variables'
  , 'var b = a++;'
  , ''
  , '// more examples'
  , '\'http://thlorenz.com/blog/scriptie-talkie\';'
].join('\n');
